import { SocialBannerProps } from "./SocialBanner";

// Dummy data for LinkedIn social banners
export const linkedInBannerTemplates: SocialBannerProps[] = [
    {
        id: 1,
        title: "Professional Portfolio",
        description: "Showcase your work experience and skills",
        gradientFrom: "orange-500",
        gradientVia: "pink-600",
        gradientTo: "purple-700",
        logoPosition: "left",
        textPosition: "right",
        textColor: "text-white",
        logoUrl: "/placeholder.svg?height=32&width=32",
    },
    {
        id: 2,
        title: "Tech Innovator",
        description: "Highlight your technical expertise",
        gradientFrom: "blue-500",
        gradientVia: "indigo-600",
        gradientTo: "purple-700",
        logoPosition: "center",
        textPosition: "center",
        textColor: "text-white",
    },
    {
        id: 3,
        title: "Creative Designer",
        description: "Showcase your creative portfolio",
        gradientFrom: "pink-500",
        gradientVia: "rose-600",
        gradientTo: "red-700",
        logoPosition: "right",
        textPosition: "left",
        textColor: "text-white",
        logoUrl: "/placeholder.svg?height=32&width=32",
    },
    {
        id: 4,
        title: "Business Professional",
        description: "Establish your corporate presence",
        gradientFrom: "emerald-500",
        gradientVia: "teal-600",
        gradientTo: "cyan-700",
        logoPosition: "left",
        textPosition: "left",
        textColor: "text-white",
    },
    {
        id: 5,
        title: "Startup Founder",
        description: "Share your entrepreneurial journey",
        gradientFrom: "amber-500",
        gradientVia: "orange-600",
        gradientTo: "red-700",
        logoPosition: "right",
        textPosition: "right",
        textColor: "text-white",
        logoUrl: "/placeholder.svg?height=32&width=32",
    },
]
