import { SocialBannerProps } from "./SocialBanner";

export const linkedInBannerTemplates: SocialBannerProps[] = [
  {
    id: 1,
    title: "Professional Blue",
    description: "Classic professional gradient for corporate profiles",
    gradientFrom: "blue-600",
    gradientVia: "blue-500",
    gradientTo: "indigo-700",
    logoPosition: "left",
    textPosition: "right",
    textColor: "text-white",
    logoUrl: "/logos/corporate.svg",
  },
  {
    id: 2,
    title: "Creative Purple",
    description: "Stand out with a vibrant creative gradient",
    gradientFrom: "purple-600",
    gradientVia: "fuchsia-500",
    gradientTo: "pink-600",
    logoPosition: "right",
    textPosition: "left",
    textColor: "text-white",
    logoUrl: "/logos/creative.svg",
  },
  {
    id: 3,
    title: "Tech Innovation",
    description: "Modern tech-inspired gradient for innovators",
    gradientFrom: "cyan-500",
    gradientVia: "teal-400",
    gradientTo: "emerald-600",
    logoPosition: "left",
    textPosition: "left",
    textColor: "text-white",
    logoUrl: "/logos/tech.svg",
  },
  {
    id: 4,
    title: "Sunset Vibes",
    description: "Warm gradient for a friendly approachable profile",
    gradientFrom: "orange-500",
    gradientVia: "amber-400",
    gradientTo: "yellow-300",
    logoPosition: "center",
    textPosition: "center",
    textColor: "text-gray-800",
    logoUrl: "/logos/friendly.svg",
  },
  {
    id: 5,
    title: "Deep Ocean",
    description: "Professional dark blue gradient for finance & consulting",
    gradientFrom: "blue-900",
    gradientVia: "blue-800",
    gradientTo: "blue-700",
    logoPosition: "left",
    textPosition: "right",
    textColor: "text-white",
    logoUrl: "/logos/finance.svg",
  },
  {
    id: 6,
    title: "Elegant Slate",
    description: "Sophisticated gradient for executive profiles",
    gradientFrom: "slate-700",
    gradientVia: "slate-600",
    gradientTo: "slate-500",
    logoPosition: "left",
    textPosition: "right",
    textColor: "text-white",
    logoUrl: "/logos/executive.svg",
  },
  {
    id: 7,
    title: "Vibrant Energy",
    description: "Bold gradient for marketing & sales professionals",
    gradientFrom: "fuchsia-600",
    gradientVia: "purple-600",
    gradientTo: "violet-700",
    logoPosition: "right",
    textPosition: "left",
    textColor: "text-white",
    logoUrl: "/logos/marketing.svg",
  },
  {
    id: 8,
    title: "Emerald Success",
    description: "Growth-inspired gradient for entrepreneurs",
    gradientFrom: "emerald-600",
    gradientVia: "emerald-500",
    gradientTo: "teal-500",
    logoPosition: "left",
    textPosition: "center",
    textColor: "text-white",
    logoUrl: "/logos/growth.svg",
  },
  {
    id: 9,
    title: "Autumn Warmth",
    description: "Inviting gradient for education & coaching",
    gradientFrom: "amber-600",
    gradientVia: "amber-500",
    gradientTo: "orange-500",
    logoPosition: "center",
    textPosition: "center",
    textColor: "text-white",
    logoUrl: "/logos/education.svg",
  },
  {
    id: 10,
    title: "Minimal Monochrome",
    description: "Clean black & white gradient for minimalists",
    gradientFrom: "gray-900",
    gradientVia: "gray-800",
    gradientTo: "gray-700",
    logoPosition: "left",
    textPosition: "right",
    textColor: "text-white",
    logoUrl: "/logos/minimal.svg",
  },
  {
    id: 11,
    title: "Rose Gold",
    description: "Luxury gradient for premium services & products",
    gradientFrom: "rose-400",
    gradientVia: "pink-300",
    gradientTo: "rose-200",
    logoPosition: "right",
    textPosition: "left",
    textColor: "text-gray-800",
    logoUrl: "/logos/luxury.svg",
  },
  {
    id: 12,
    title: "Health & Wellness",
    description: "Calming gradient for healthcare professionals",
    gradientFrom: "green-400",
    gradientVia: "teal-300",
    gradientTo: "emerald-400",
    logoPosition: "left",
    textPosition: "center",
    textColor: "text-gray-800",
    logoUrl: "/logos/health.svg",
  },
] as const;
